server:
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.111.99.207
    port: 6379
    password: d52cKyUm9jgbdie3YW4e
    valid: true
    database: 116
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
    serialization:
      fail-on-empty-beans: false

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      use-new-id-generator-mappings: false
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

